version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/symfony

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - symfony_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
